AWSTemplateFormatVersion: "2010-09-09"
Description: CodePipeline pipeline (GitHub -> CodeBuild) with S3 artifact bucket.

Parameters:
  GitHubOwner:
    Type: String
    Description: GitHub username or org that owns the repository
  GitHubRepo:
    Type: String
    Description: GitHub repository name
  GitHubBranch:
    Type: String
    Default: master
    Description: Branch to build
  GitHubAccessToken:
    Type: String
    NoEcho: true
    Description: GitHub OAuth token (use a Personal Access Token or Secrets Manager dynamic ref)

Resources:

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  # Role used by CodePipeline to access S3 and start CodeBuild
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Path: /service-role/
      Policies:
        - PolicyName: CodePipelineAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !Sub "${ArtifactBucket.Arn}/*"
              - Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Resource:
                  - !GetAtt AppBuildProject.Arn

  # Role for CodeBuild (allows logs, s3 access)
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess  # for demo; tighten in production

  # CodeBuild project that expects source from CodePipeline
  AppBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: java-app-build
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
        PrivilegedMode: false
      Artifacts:
        Type: CODEPIPELINE
      TimeoutInMinutes: 30

  # CodePipeline pipeline
  AppPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: java-app-pipeline
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub_Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubAccessToken
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              Configuration:
                ProjectName: !Ref AppBuildProject
              RunOrder: 1

Outputs:
  PipelineName:
    Description: "CodePipeline name"
    Value: !Ref AppPipeline
  ArtifactBucketName:
    Description: "S3 bucket for pipeline artifacts"
    Value: !Ref ArtifactBucket
